device_name = "can-io"
heartbeat_period = 1000

[identity]
vendor_id = 0xCAFE
product_code = 1032
revision_number = 1

[[objects]]
index = 0x2000
parameter_name = "Raw Analog Input"
object_type = "array"
data_type = "uint16"
access_type = "ro"
array_size = 4
default_value = [0, 0, 0, 0]
pdo_mapping = "tpdo"

[[objects]]
index = 0x2001
parameter_name = "Scaled Analog Input I32"
object_type = "array"
data_type = "int32"
access_type = "ro"
array_size = 4
default_value = [0, 0, 0, 0]
pdo_mapping = "tpdo"

[[objects]]
index = 0x2002
parameter_name = "Scaled Analog Input I16"
object_type = "array"
data_type = "int16"
access_type = "ro"
array_size = 4
default_value = [0, 0, 0, 0]
pdo_mapping = "tpdo"

[[objects]]
index = 0x2100
parameter_name = "Analog Read Period (ms)"
object_type = "var"
data_type = "uint32"
access_type = "rw"
default_value = 10
persist = true

[[objects]]
index = 0x2101
parameter_name = "Analog Scale Config"
object_type = "record"
[[objects.subs]]
sub_index = 1
parameter_name = "Scale Numerator"
field_name = "scale_numerator"
data_type = "uint16"
access_type = "rw"
default_value = 1
persist = true
[[objects.subs]]
sub_index = 2
parameter_name = "Scale Denominator"
field_name = "scale_denominator"
data_type = "uint16"
access_type = "rw"
default_value = 1
persist = true
[[objects.subs]]
sub_index = 3
parameter_name = "Offset"
field_name = "offset"
data_type = "uint16"
access_type = "rw"
default_value = 0
persist = true



